// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinitionGetter } from '../types';
const temp: any = function CanlendarTwoTone(
  primaryColor: string,
  secondaryColor: string
) {
  return {
    name: 'canlendar',
    theme: 'twotone',
    nameWithTheme: 'canlendar-twotone',
    tag: 'svg',
    attrs: {
      xmlns: 'http://www.w3.org/2000/svg',
      class: 'icon',
      viewBox: '0 0 1024 1024'
    },
    children: [
      {
        tag: 'path',
        attrs: {
          fill: secondaryColor,
          d:
            'M712 304c0 4.4-3.6 8-8 8h-56c-4.4 0-8-3.6-8-8v-48H384v48c0 4.4-3.6 8-8 8h-56c-4.4 0-8-3.6-8-8v-48H184v136h656V256H712v48z'
        },
        children: []
      },
      {
        tag: 'path',
        attrs: {
          d:
            'M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zm0-448H184V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136z',
          fill: primaryColor
        },
        children: []
      }
    ]
  };
};
temp.nameWithTheme = 'canlendar-twotone';
const CanlendarTwoTone: IconDefinitionGetter = temp;
export default CanlendarTwoTone;
