// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinitionGetter } from '../types';
const temp: any = function CheckSquareTwoTone(
  primaryColor: string,
  secondaryColor: string
) {
  return {
    name: 'check-square',
    theme: 'twotone',
    nameWithTheme: 'check-square-twotone',
    tag: 'svg',
    attrs: {
      xmlns: 'http://www.w3.org/2000/svg',
      class: 'icon',
      viewBox: '0 0 1024 1024'
    },
    children: [
      {
        tag: 'path',
        attrs: {
          fill: primaryColor,
          d:
            'M880 112H144c-17.7 0-32 14.3-32 32v736c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V144c0-17.7-14.3-32-32-32zm-40 728H184V184h656v656z'
        },
        children: []
      },
      {
        tag: 'path',
        attrs: {
          fill: secondaryColor,
          d:
            'M184 840h656V184H184v656zm130-367.8h46.9c10.2 0 19.9 4.9 25.9 13.3l71.2 98.8 157.2-218c6-8.3 15.6-13.3 25.9-13.3H688c6.5 0 10.3 7.4 6.5 12.7l-210.6 292c-12.7 17.7-39 17.7-51.7 0L307.5 484.9c-3.8-5.3 0-12.7 6.5-12.7z'
        },
        children: []
      },
      {
        tag: 'path',
        attrs: {
          fill: primaryColor,
          d:
            'M432.2 657.7c12.7 17.7 39 17.7 51.7 0l210.6-292c3.8-5.3 0-12.7-6.5-12.7h-46.9c-10.3 0-19.9 5-25.9 13.3L458 584.3l-71.2-98.8c-6-8.4-15.7-13.3-25.9-13.3H314c-6.5 0-10.3 7.4-6.5 12.7l124.7 172.8z'
        },
        children: []
      }
    ]
  };
};
temp.nameWithTheme = 'check-square-twotone';
const CheckSquareTwoTone: IconDefinitionGetter = temp;
export default CheckSquareTwoTone;
