// This icon file is generated by build/generateIcons.ts
// tslint:disable

import { IconDefinitionGetter } from '../types';
const temp: any = function PoweroffCircleTwotTwoTone(
  primaryColor: string,
  secondaryColor: string
) {
  return {
    name: 'poweroff-circle-twot',
    theme: 'twotone',
    nameWithTheme: 'poweroff-circle-twot-twotone',
    tag: 'svg',
    attrs: {
      xmlns: 'http://www.w3.org/2000/svg',
      class: 'icon',
      viewBox: '0 0 1024 1024'
    },
    children: [
      {
        tag: 'path',
        attrs: {
          fill: primaryColor,
          d:
            'M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm0 820c-205.4 0-372-166.6-372-372s166.6-372 372-372 372 166.6 372 372-166.6 372-372 372z'
        },
        children: []
      },
      {
        tag: 'path',
        attrs: {
          fill: secondaryColor,
          d:
            'M512 140c-205.4 0-372 166.6-372 372s166.6 372 372 372 372-166.6 372-372-166.6-372-372-372zm-80 524c0 4.4-3.6 8-8 8h-48c-4.4 0-8-3.6-8-8V360c0-4.4 3.6-8 8-8h48c4.4 0 8 3.6 8 8v304zm224 0c0 4.4-3.6 8-8 8h-48c-4.4 0-8-3.6-8-8V360c0-4.4 3.6-8 8-8h48c4.4 0 8 3.6 8 8v304z'
        },
        children: []
      },
      {
        tag: 'path',
        attrs: {
          fill: primaryColor,
          d:
            'M424 352h-48c-4.4 0-8 3.6-8 8v304c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V360c0-4.4-3.6-8-8-8zm224 0h-48c-4.4 0-8 3.6-8 8v304c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V360c0-4.4-3.6-8-8-8z'
        },
        children: []
      }
    ]
  };
};
temp.nameWithTheme = 'poweroff-circle-twot-twotone';
const PoweroffCircleTwotTwoTone: IconDefinitionGetter = temp;
export default PoweroffCircleTwotTwoTone;
