// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import AnthropicFilledSvg from '@ant-design/icons-svg/lib/asn/AnthropicFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const AnthropicFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={AnthropicFilledSvg} />;

 /**![anthropic](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTcxMC4wMiAxOTYuMkg1NzIuOTRsMjQ5Ljk4IDYzMS42SDk2MHptLTM5Ni4wNCAwTDY0IDgyNy44aDEzOS43OGw1MS4xMi0xMzIuNjNoMjYxLjUzbDUxLjEyIDEzMi42NGgxMzkuNzlMNDU3LjM2IDE5Ni4xOXptLTEzLjg2IDM4MS42Nmw4NS41NS0yMjEuOTcgODUuNTQgMjIxLjk3eiIgLz48L3N2Zz4=) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(AnthropicFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'AnthropicFilled';
}

export default RefIcon;