// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import CFilledSvg from '@ant-design/icons-svg/lib/asn/CFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const CFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={CFilledSvg} />;

 /**![c](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTY4My40NCA0MDcuMzJTNjcwLjIyIDI4NC4yIDU0OC4wMyAyODAuNzZjLTEyMi4yMy0zLjM2LTE4NSA5Mi4zNy0xODUgMjI5LjIzIDAgMTM2LjgzIDY5LjM3IDI0Ni4zIDE4OC4zNiAyNDYuMyAxMTguODcgMCAxMzIuMDktMTM2LjgzIDEzMi4wOS0xMzYuODNsMjI3Ljg4IDEzLjYzczEzLjQ0IDEyMy41Ny04MS45OCAyMTcuODdDNzM0LjEgOTQ1LjIgNjE2Ljk1IDk2MC42MiA1MzUuMzMgOTU5Ljk4Yy04MS43Ni0uNjMtMTk1LjEgMS4yNy0zMDQuNjQtMTEwLjg4QzEyMSA3MzYuNzIgMTAyLjQgNjI3LjcgMTAyLjQgNTIwLjU2YzAtMTA3LjE1IDIwLjc2LTI0OS4wMiAxNTEuMDktMzU2LjU0QzM0MS45IDkwLjg4IDQzMS43IDY0IDUyMS40OCA2NCA4OTYuNCA2NCA5MjEuNiA0MDkuNzEgOTIxLjYgNDA5LjcxeiIgLz48L3N2Zz4=) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(CFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'CFilled';
}

export default RefIcon;