// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import ElevenLabsFilledSvg from '@ant-design/icons-svg/lib/asn/ElevenLabsFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const ElevenLabsFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={ElevenLabsFilledSvg} />;

 /**![eleven-labs](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTIzNS44NiA2NHY4OTZoMTg0LjEyVjY0em0zNjguMTYgMHY4OTZoMTg0LjEyVjY0eiIgLz48L3N2Zz4=) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(ElevenLabsFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'ElevenLabsFilled';
}

export default RefIcon;