// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import FileVideoFilledSvg from '@ant-design/icons-svg/lib/asn/FileVideoFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const FileVideoFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={FileVideoFilledSvg} />;

 /**![file-video](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTg1NC42IDI4OC43TDYzOS40IDczLjRjLTYtNi0xNC4yLTkuNC0yMi43LTkuNEgxOTJjLTE3LjcgMC0zMiAxNC4zLTMyIDMydjgzMmMwIDE3LjcgMTQuMyAzMiAzMiAzMmg2NDBjMTcuNyAwIDMyLTE0LjMgMzItMzJWMzExLjNjMC04LjUtMy40LTE2LjYtOS40LTIyLjZ6TTYwMiAzMjZWMTM3LjhMNzkwLjIgMzI2ek00NDUuNzkgNzAwLjgzbDE2My41LTEyOC41YTkuMjcgOS4yNyAwIDAwMC0xNC41TDQ0NS44IDQyOS4yNGMtNi4wNy00Ljc2LTE1LjAxLS41LTE1LjAxIDcuMjF2MjU3LjA3YTkuMyA5LjMgMCAwMDE1IDcuM3oiIGZpbGwtcnVsZT0iZXZlbm9kZCIgLz48L3N2Zz4=) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(FileVideoFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'FileVideoFilled';
}

export default RefIcon;