// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import FileVideoTwoToneSvg from '@ant-design/icons-svg/lib/asn/FileVideoTwoTone';
import AntdIcon from '../components/AntdIcon';
import type { AntdIconProps } from '../components/AntdIcon';

const FileVideoTwoTone = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={FileVideoTwoToneSvg} />;

 /**![file-video](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTUzNCAzNTJWMTM2SDIzMnY3NTJoNTYwVjM5NEg1NzZhNDIgNDIgMCAwMS00Mi00MnptLTg4LjIxIDM0OC44M2E5LjMgOS4zIDAgMDEtMTUtNy4zMVY0MzYuNDVjMC03LjcxIDguOTQtMTEuOTcgMTUuMDEtNy4yMWwxNjMuNDkgMTI4LjU5YTkuMjcgOS4yNyAwIDAxMCAxNC41bC0xNjMuNSAxMjguNXoiIGZpbGw9IiNlNmY0ZmYiIC8+PHBhdGggZD0iTTg1NC42IDI4OC42TDYzOS40IDczLjRjLTYtNi0xNC4xLTkuNC0yMi42LTkuNEgxOTJjLTE3LjcgMC0zMiAxNC4zLTMyIDMydjgzMmMwIDE3LjcgMTQuMyAzMiAzMiAzMmg2NDBjMTcuNyAwIDMyLTE0LjMgMzItMzJWMzExLjNjMC04LjUtMy40LTE2LjctOS40LTIyLjd6TTYwMiAxMzcuOEw3OTAuMiAzMjZINjAyVjEzNy44ek03OTIgODg4SDIzMlYxMzZoMzAydjIxNmE0MiA0MiAwIDAwNDIgNDJoMjE2djQ5NHoiIGZpbGw9IiMxNjc3ZmYiIC8+PHBhdGggZD0iTTQ0NS43OSA3MDAuODNsMTYzLjUtMTI4LjVhOS4yNyA5LjI3IDAgMDAwLTE0LjVMNDQ1LjggNDI5LjI0Yy02LjA3LTQuNzYtMTUuMDEtLjUtMTUuMDEgNy4yMXYyNTcuMDdhOS4zIDkuMyAwIDAwMTUgNy4zeiIgZmlsbD0iIzE2NzdmZiIgLz48L3N2Zz4=) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(FileVideoTwoTone);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'FileVideoTwoTone';
}

export default RefIcon;