// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import FunctionOutlinedSvg from '@ant-design/icons-svg/lib/asn/FunctionOutlined';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const FunctionOutlined = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={FunctionOutlinedSvg} />;

 /**![function](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTg0MSAzNzBjMy0zLjMgMi43LTguMy0uNi0xMS4zYTguMjQgOC4yNCAwIDAwLTUuMy0yLjFoLTcyLjZjLTIuNCAwLTQuNiAxLTYuMSAyLjhMNjMzLjUgNTA0LjZhNy45NiA3Ljk2IDAgMDEtMTMuNC0xLjlsLTYzLjUtMTQxLjNhNy45IDcuOSAwIDAwLTcuMy00LjdIMzgwLjdsLjktNC43IDgtNDIuM2MxMC41LTU1LjQgMzgtODEuNCA4NS44LTgxLjQgMTguNiAwIDM1LjUgMS43IDQ4LjggNC43bDE0LjEtNjYuOGMtMjIuNi00LjctMzUuMi02LjEtNTQuOS02LjEtMTAzLjMgMC0xNTYuNCA0NC4zLTE3NS45IDE0Ny4zbC05LjQgNDkuNGgtOTcuNmMtMy44IDAtNy4xIDIuNy03LjggNi40TDE4MS45IDQxNWE4LjA3IDguMDcgMCAwMDcuOCA5LjdIMjg0bC04OSA0MjkuOWE4LjA3IDguMDcgMCAwMDcuOCA5LjdIMjY5YzMuOCAwIDcuMS0yLjcgNy44LTYuNGw4OS43LTQzMy4xaDEzNS44bDY4LjIgMTM5LjFjMS40IDIuOSAxIDYuNC0xLjIgOC44bC0xODAuNiAyMDNjLTIuOSAzLjMtMi42IDguNC43IDExLjMgMS41IDEuMyAzLjQgMiA1LjMgMmg3Mi43YzIuNCAwIDQuNi0xIDYuMS0yLjhsMTIzLjctMTQ2LjdjMi44LTMuNCA3LjktMy44IDExLjMtMSAuOS44IDEuNiAxLjcgMi4xIDIuOEw2NzYuNCA3ODRjMS4zIDIuOCA0LjEgNC43IDcuMyA0LjdoNjQuNmE4LjAyIDguMDIgMCAwMDcuMi0xMS41bC05NS4yLTE5OC45Yy0xLjQtMi45LS45LTYuNCAxLjMtOC44TDg0MSAzNzB6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(FunctionOutlined);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'FunctionOutlined';
}

export default RefIcon;