// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import GifOutlinedSvg from '@ant-design/icons-svg/lib/asn/GifOutlined';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const GifOutlined = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={GifOutlinedSvg} />;

 /**![gif](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTk0NCAyOTlINjkyYy00LjQgMC04IDMuNi04IDh2NDA2YzAgNC40IDMuNiA4IDggOGg1OS4yYzQuNCAwIDgtMy42IDgtOFY1NDkuOWgxNjguMmM0LjQgMCA4LTMuNiA4LThWNDk1YzAtNC40LTMuNi04LTgtOEg3NTkuMlYzNjQuMkg5NDRjNC40IDAgOC0zLjYgOC04VjMwN2MwLTQuNC0zLjYtOC04LTh6bS0zNTYgMWgtNTZjLTQuNCAwLTggMy42LTggOHY0MDZjMCA0LjQgMy42IDggOCA4aDU2YzQuNCAwIDgtMy42IDgtOFYzMDhjMC00LjQtMy42LTgtOC04ek00NTIgNTAwLjlIMjkwLjVjLTQuNCAwLTggMy42LTggOHY0My43YzAgNC40IDMuNiA4IDggOGg5NC45bC0uMyA4LjljLTEuMiA1OC44LTQ1LjYgOTguNS0xMTAuOSA5OC41LTc2LjIgMC0xMjMuOS01OS43LTEyMy45LTE1Ni43IDAtOTUuOCA0Ni44LTE1NS4yIDEyMS41LTE1NS4yIDU0LjggMCA5My4xIDI2LjkgMTA4LjUgNzUuNGg3Ni4yYy0xMy42LTg3LjItODYtMTQzLjQtMTg0LjctMTQzLjRDMTUwIDI4OCA3MiAzNzUuMiA3MiA1MTEuOSA3MiA2NTAuMiAxNDkuMSA3MzYgMjczIDczNmMxMTQuMSAwIDE4Ny03MC43IDE4Ny0xODEuNnYtNDUuNWMwLTQuNC0zLjYtOC04LTh6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(GifOutlined);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'GifOutlined';
}

export default RefIcon;