// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import GraphQLFilledSvg from '@ant-design/icons-svg/lib/asn/GraphQLFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const GraphQLFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={GraphQLFilledSvg} />;

 /**![graph-q-l](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTUxMi4wNyA2NGE3OS44NCA3OS44NCAwIDEwMCAxNTkuNjcgNzkuODQgNzkuODQgMCAxMDAtMTU5LjY3ek04MzAuOSAyNDguMWE3OS44NCA3OS44NCAwIDEwMCAxNTkuNjcgNzkuODQgNzkuODQgMCAxMDAtMTU5LjY4em0wIDM2OC4xN2E3OS44NCA3OS44NCAwIDEwMCAxNTkuNjggNzkuODQgNzkuODQgMCAxMDAtMTU5LjY4em0tMzE4LjgzIDE4NC4xYTc5LjgyIDc5LjgyIDAgMTAwIDE1OS42MyA3OS44MiA3OS44MiAwIDEwMC0xNTkuNjR6TTE5My4xNyA2MTYuM2E3OS44MiA3OS44MiAwIDEwMCAxNTkuNjQgNzkuODQgNzkuODQgMCAxMDAtMTU5LjY4em0wLTM2OC4yMmE3OS44NCA3OS44NCAwIDEwMCAxNTkuNjggNzkuODQgNzkuODQgMCAxMDAtMTU5LjY4em0zMTguOS0xMjYuMTFMMTc0LjI1IDMxN3YzOTAuMDZMNTEyLjA3IDkwMi4xbDMzNy43Ni0xOTUuMDNWMzE3em0wIDU5Ljc3bDI4NS45OCA0OTUuNDFIMjI2LjAzek00NjAuMyAxOTUuNkwyMTIuMjEgNjI1LjM4di0yODYuNXptMTAzLjU3IDBsMjQ4LjExIDE0My4yOXYyODYuNXpNMjYzLjkyIDcxNS4xaDQ5Ni4yN0w1MTIuMDcgODU4LjN6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(GraphQLFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'GraphQLFilled';
}

export default RefIcon;