// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import InsertRowBelowOutlinedSvg from '@ant-design/icons-svg/lib/asn/InsertRowBelowOutlined';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const InsertRowBelowOutlined = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={InsertRowBelowOutlinedSvg} />;

 /**![insert-row-below](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTkwNCA3NjhIMTIwYy00LjQgMC04IDMuNi04IDh2ODBjMCA0LjQgMy42IDggOCA4aDc4NGM0LjQgMCA4LTMuNiA4LTh2LTgwYzAtNC40LTMuNi04LTgtOHptLTI1LjMtNjA4SDE0NS4zYy0xOC40IDAtMzMuMyAxNC4zLTMzLjMgMzJ2NDY0YzAgMTcuNyAxNC45IDMyIDMzLjMgMzJoNzMzLjNjMTguNCAwIDMzLjMtMTQuMyAzMy4zLTMyVjE5MmMuMS0xNy43LTE0LjgtMzItMzMuMi0zMnpNMzYwIDYxNkgxODRWNDU2aDE3NnYxNjB6bTAtMjI0SDE4NFYyMzJoMTc2djE2MHptMjQwIDIyNEg0MjRWNDU2aDE3NnYxNjB6bTAtMjI0SDQyNFYyMzJoMTc2djE2MHptMjQwIDIyNEg2NjRWNDU2aDE3NnYxNjB6bTAtMjI0SDY2NFYyMzJoMTc2djE2MHoiIC8+PC9zdmc+) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(InsertRowBelowOutlined);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'InsertRowBelowOutlined';
}

export default RefIcon;