// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import MacCommandFilledSvg from '@ant-design/icons-svg/lib/asn/MacCommandFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const MacCommandFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={MacCommandFilledSvg} />;

 /**![mac-command](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTYyNCA2NzJhNDguMDEgNDguMDEgMCAwMDk2IDBjMC0yNi41LTIxLjUtNDgtNDgtNDhoLTQ4djQ4em05Ni0zMjBhNDguMDEgNDguMDEgMCAwMC05NiAwdjQ4aDQ4YzI2LjUgMCA0OC0yMS41IDQ4LTQ4eiIgLz48cGF0aCBkPSJNOTI4IDY0SDk2Yy0xNy43IDAtMzIgMTQuMy0zMiAzMnY4MzJjMCAxNy43IDE0LjMgMzIgMzIgMzJoODMyYzE3LjcgMCAzMi0xNC4zIDMyLTMyVjk2YzAtMTcuNy0xNC4zLTMyLTMyLTMyek02NzIgNTYwYzYxLjkgMCAxMTIgNTAuMSAxMTIgMTEycy01MC4xIDExMi0xMTIgMTEyLTExMi01MC4xLTExMi0xMTJ2LTQ4aC05NnY0OGMwIDYxLjktNTAuMSAxMTItMTEyIDExMnMtMTEyLTUwLjEtMTEyLTExMiA1MC4xLTExMiAxMTItMTEyaDQ4di05NmgtNDhjLTYxLjkgMC0xMTItNTAuMS0xMTItMTEyczUwLjEtMTEyIDExMi0xMTIgMTEyIDUwLjEgMTEyIDExMnY0OGg5NnYtNDhjMC02MS45IDUwLjEtMTEyIDExMi0xMTJzMTEyIDUwLjEgMTEyIDExMi01MC4xIDExMi0xMTIgMTEyaC00OHY5Nmg0OHoiIC8+PHBhdGggZD0iTTQ2NCA0NjRoOTZ2OTZoLTk2ek0zNTIgMzA0YTQ4LjAxIDQ4LjAxIDAgMDAwIDk2aDQ4di00OGMwLTI2LjUtMjEuNS00OC00OC00OHptLTQ4IDM2OGE0OC4wMSA0OC4wMSAwIDAwOTYgMHYtNDhoLTQ4Yy0yNi41IDAtNDggMjEuNS00OCA0OHoiIC8+PC9zdmc+) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(MacCommandFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'MacCommandFilled';
}

export default RefIcon;