// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import MarkdownFilledSvg from '@ant-design/icons-svg/lib/asn/MarkdownFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const MarkdownFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={MarkdownFilledSvg} />;

 /**![markdown](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTg5NS40MSA3ODcuN0gxMjguNkE2NC41OSA2NC41OSAwIDAxNjQgNzIzLjEzVjMwMC44OGE2NC41OSA2NC41OSAwIDAxNjQuNTktNjQuNTlIODk1LjRBNjQuNTkgNjQuNTkgMCAwMTk2MCAzMDAuODh2NDIyLjE3YTY0LjU5IDY0LjU5IDAgMDEtNjQuNTkgNjQuNjJ6TTI3OS4zOCA2NTguNDd2LTE2OGw4Ni4xNiAxMDcuNyA4Ni4xMy0xMDcuN3YxNjhoODYuMTZWMzY1LjU4aC04Ni4xNmwtODYuMTMgMTA3LjctODYuMTYtMTA3LjdoLTg2LjJ2MjkyLjk1ek04NTYuNjYgNTEyaC04Ni4yVjM2NS41NGgtODYuMTNWNTEyaC04Ni4xNmwxMjkuMiAxNTAuNzl6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(MarkdownFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'MarkdownFilled';
}

export default RefIcon;