// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import MergeCellsOutlinedSvg from '@ant-design/icons-svg/lib/asn/MergeCellsOutlined';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const MergeCellsOutlined = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={MergeCellsOutlinedSvg} />;

 /**![merge-cells](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTQ4Mi4yIDUwOC40TDMzMS4zIDM4OWMtMy0yLjQtNy4zLS4yLTcuMyAzLjZWNDc4SDE4NFYxODRoMjA0djEyOGMwIDIuMiAxLjggNCA0IDRoNjBjMi4yIDAgNC0xLjggNC00VjE0NGMwLTE1LjUtMTIuNS0yOC0yOC0yOEgxNDRjLTE1LjUgMC0yOCAxMi41LTI4IDI4djczNmMwIDE1LjUgMTIuNSAyOCAyOCAyOGgyODRjMTUuNSAwIDI4LTEyLjUgMjgtMjhWNzEyYzAtMi4yLTEuOC00LTQtNGgtNjBjLTIuMiAwLTQgMS44LTQgNHYxMjhIMTg0VjU0NmgxNDB2ODUuNGMwIDMuOCA0LjQgNiA3LjMgMy42bDE1MC45LTExOS40YTQuNSA0LjUgMCAwMDAtNy4yek04ODAgMTE2SDU5NmMtMTUuNSAwLTI4IDEyLjUtMjggMjh2MTY4YzAgMi4yIDEuOCA0IDQgNGg2MGMyLjIgMCA0LTEuOCA0LTRWMTg0aDIwNHYyOTRINzAwdi04NS40YzAtMy44LTQuMy02LTcuMy0zLjZsLTE1MSAxMTkuNGE0LjUyIDQuNTIgMCAwMDAgNy4xbDE1MSAxMTkuNWMyLjkgMi4zIDcuMy4yIDcuMy0zLjZWNTQ2aDE0MHYyOTRINjM2VjcxMmMwLTIuMi0xLjgtNC00LTRoLTYwYy0yLjIgMC00IDEuOC00IDR2MTY4YzAgMTUuNSAxMi41IDI4IDI4IDI4aDI4NGMxNS41IDAgMjgtMTIuNSAyOC0yOFYxNDRjMC0xNS41LTEyLjUtMjgtMjgtMjh6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(MergeCellsOutlined);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'MergeCellsOutlined';
}

export default RefIcon;