// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import NetflixFilledSvg from '@ant-design/icons-svg/lib/asn/NetflixFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const NetflixFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={NetflixFilledSvg} />;

 /**![netflix](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTI2NS41MyA2NGwzMTEuNjUgODgxLjE0Yzg3LjU5IDIuMiAxODEuMyAxNC44NiAxODEuMyAxNC44Nkw0NDEuNTQgNjRIMjY1LjUzem0zMTYuOTIgMHYzNDIuNDJsMTc2LjAyIDQ5Ny42NVY2NEg1ODIuNDV6bS0zMTYuOTIgNTZ2ODQwYzY5LjkyLTguNCAxMDQuOS0xMS42NSAxNzYuMDItMTQuODZWNjE3LjY1TDI2NS41MyAxMjB6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(NetflixFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'NetflixFilled';
}

export default RefIcon;