// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import PartitionOutlinedSvg from '@ant-design/icons-svg/lib/asn/PartitionOutlined';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const PartitionOutlined = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={PartitionOutlinedSvg} />;

 /**![partition](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTY0MC42IDQyOS44aDI1Ny4xYzcuOSAwIDE0LjMtNi40IDE0LjMtMTQuM1YxNTguM2MwLTcuOS02LjQtMTQuMy0xNC4zLTE0LjNINjQwLjZjLTcuOSAwLTE0LjMgNi40LTE0LjMgMTQuM3Y5Mi45SDQ5MC42Yy0zLjkgMC03LjEgMy4yLTcuMSA3LjF2MjIxLjVoLTg1Ljd2LTk2LjVjMC03LjktNi40LTE0LjMtMTQuMy0xNC4zSDEyNi4zYy03LjkgMC0xNC4zIDYuNC0xNC4zIDE0LjN2MjU3LjJjMCA3LjkgNi40IDE0LjMgMTQuMyAxNC4zaDI1Ny4xYzcuOSAwIDE0LjMtNi40IDE0LjMtMTQuM1Y1NDRoODUuN3YyMjEuNWMwIDMuOSAzLjIgNy4xIDcuMSA3LjFoMTM1Ljd2OTIuOWMwIDcuOSA2LjQgMTQuMyAxNC4zIDE0LjNoMjU3LjFjNy45IDAgMTQuMy02LjQgMTQuMy0xNC4zdi0yNTdjMC03LjktNi40LTE0LjMtMTQuMy0xNC4zaC0yNTdjLTcuOSAwLTE0LjMgNi40LTE0LjMgMTQuM3YxMDBoLTc4LjZ2LTM5M2g3OC42djEwMGMwIDcuOSA2LjQgMTQuMyAxNC4zIDE0LjN6bTUzLjUtMjE3LjloMTUwVjM2MmgtMTUwVjIxMS45ek0zMjkuOSA1ODdoLTE1MFY0MzdoMTUwdjE1MHptMzY0LjIgNzUuMWgxNTB2MTUwLjFoLTE1MFY2NjIuMXoiIC8+PC9zdmc+) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(PartitionOutlined);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'PartitionOutlined';
}

export default RefIcon;