// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import PerplexityFilledSvg from '@ant-design/icons-svg/lib/asn/PerplexityFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const PerplexityFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={PerplexityFilledSvg} />;

 /**![perplexity](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTkwMC4xOCAzMjguNjhoLTg2LjI2VjY2LjUyTDUzMy41NyAzMDMuNzVWNjkuODloLTQzLjE0djIzMS4zNEwyMzEuNjQgNjR2MjY0LjY4SDEyMy44MnYzODguMThoMTA3LjgzVjk2MGwyNTguNzktMjM3LjR2MjMxLjQ4aDQzLjEzVjcyOC4zM2wyNTguOCAyMzAuNzRWNzE2Ljg2aDEwNy44MlYzMjguNjh6TTc3MC44IDE1OS41MnYxNjkuMTZINTcwLjg3TDc3MC44IDE1OS41MnptLTQ5Ni4wMSAyLjUybDE4MS43OCAxNjYuNjRIMjc0Ljc4VjE2Mi4wNHpNMTY2Ljk1IDY3My43M1YzNzEuOGgyOTIuOThMMjMxLjYzIDYwMC4xdjczLjYzaC02NC42OHpNMjc0Ljc4IDg2MS45VjYxNy45NmwyMTUuNjUtMjE1LjY1djI2MS43NUwyNzQuNzggODYxLjl6bTQ3NC40NS45M2wtMjE1LjY2LTE5Mi4zVjQwMi4zbDIxNS42NiAyMTUuNjZ2MjQ0Ljg2em0xMDcuODMtMTg5LjFoLTY0LjdWNjAwLjFMNTY0LjA3IDM3MS44aDI5Mi45OXYzMDEuOTJ6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(PerplexityFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'PerplexityFilled';
}

export default RefIcon;