// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import TwitchFilledSvg from '@ant-design/icons-svg/lib/asn/TwitchFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const TwitchFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={TwitchFilledSvg} />;

 /**![twitch](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIGZpbGwtcnVsZT0iZXZlbm9kZCIgdmlld0JveD0iNjQgNjQgODk2IDg5NiIgZm9jdXNhYmxlPSJmYWxzZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTg1LjE0IDExMkwxMjggMjU0Ljg2Vjc5Ny43aDE3MS40M1Y5MTJINDEzLjdMNTI4IDc5Ny43MWgxNDIuODZsMjAwLTIwMFYxMTJ6bTMxNC4yOSA0MjguNTdINDEzLjdWMzEwLjIxaDg1Ljcyem0yMDAgMEg2MTMuN1YzMTAuMjFoODUuNzJ6IiAvPjwvc3ZnPg==) */
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(TwitchFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'TwitchFilled';
}

export default RefIcon;