// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import XFilledSvg from '@ant-design/icons-svg/lib/asn/XFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const XFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={XFilledSvg} />;

 /**![x](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTgyMy4xMSA5MTJIMjAwLjlBODguOSA4OC45IDAgMDExMTIgODIzLjExVjIwMC45QTg4LjkgODguOSAwIDAxMjAwLjg5IDExMkg4MjMuMUE4OC45IDg4LjkgMCAwMTkxMiAyMDAuODlWODIzLjFBODguOSA4OC45IDAgMDE4MjMuMTEgOTEyTTI4NiAyOTFsMTcxLjc3IDI0NS4yOEwyODYgNzM1aDQ1LjNsMTQ2LjU3LTE3MC4wM0w1OTYuOTQgNzM1SDc0MEw1NTUuOSA0NzIuMSA3MTUgMjg5aC00NC42N0w1MzUuNzkgNDQzLjQgNDI5LjA2IDI5MXptNjkuMDUgMzcuNjVMNjE0IDY5Ny4zNWg1Ni45Nkw0MTIgMzI4LjY1aC01Ni45NnoiIGZpbGwtcnVsZT0iZXZlbm9kZCIgLz48L3N2Zz4=) */
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(XFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'XFilled';
}

export default RefIcon;