// GENERATED BY ./scripts/generate.ts
// DO NOT EDIT IT MANUALLY

import * as React from 'react'
import YamlFilledSvg from '@ant-design/icons-svg/lib/asn/YamlFilled';
import AntdIcon from '../components/AntdIconLight';
import type { AntdIconProps } from '../components/AntdIconLight';

const YamlFilled = (
  props: AntdIconProps,
  ref: React.ForwardedRef<HTMLSpanElement>,
) => <AntdIcon {...props} ref={ref} icon={YamlFilledSvg} />;

 /**![yaml](data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIGZpbGw9IiNjYWNhY2EiIHZpZXdCb3g9IjY0IDY0IDg5NiA4OTYiIGZvY3VzYWJsZT0iZmFsc2UiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTY0IDEwMC4yMWwxNTMuNDggMjQwLjkydjE1Mi42OWg5OC40OHYtMTUyLjdsMTYwLjY5LTI0MC45NGgtMTA2bC05OC4zMyAxNTUuMTUtOTcuNjMtMTU1LjE1em00NTEuNDcuOUwzNDguNiA0OTQuNzVoNzguOTJsMzYuMjItODcuNTRoMTc4LjI2bDMwLjAyIDg3LjU0aDg0LjM3bC0xNjAuMi0zOTMuNjR6bTQyLjMgODMuMDdsNTQuNjIgMTQ0LjQ4SDQ5Ni44ek02NzIuMDEgNTM3Ljl2Mzg0LjE2SDk2MHYtODIuMUg3NTYuMzhWNTM3Ljkxem0tNDU0LjUzLjA3djM4NS44NGg4Mi43N1Y2NTcuNjdsODYuNiAxNzguOWg2NS4ybDg5LjYtMTg1LjE3djI3Mi4zNWg3OS40VjUzNy45OEg1MTIuNjNsLTk2LjIgMTc0LjUtOTEuNjYtMTc0LjV6IiAvPjwvc3ZnPg==) */ 
const RefIcon: React.ForwardRefExoticComponent<
  Omit<AntdIconProps, 'ref'> & React.RefAttributes<HTMLSpanElement>
> = React.forwardRef<HTMLSpanElement, AntdIconProps>(YamlFilled);

if (process.env.NODE_ENV !== 'production') {
  RefIcon.displayName = 'YamlFilled';
}

export default RefIcon;